[package]
name = "ipc-channel-mux"
version = "0.0.10"
description = "IPC channel multiplexer"
authors = ["The Servo Project Developers"]
license = "MIT OR Apache-2.0"
repository = "https://github.com/glyn/ipc-channel-mux"
readme = "README.md"
edition = "2024"
# Keep this in sync with the msrv_build job in CI.
# This version may be `<=`, but not higher than the MSRV in the main servo project.
rust-version = "1.86.0"

[dependencies]
crossbeam-channel = "0.5"
futures-channel = { version = "0.3.31", optional = true }
futures-core = { version = "0.3.31", optional = true }
hashbag = "0.1.12"
ipc-channel = "0.21.0"
lazy_static = "1.5.0"
libc = "0.2.162"
log = "0.4.26"
postcard = { version = "1.1", default-features = false, features = ["use-std"] }
serde = { version = "1.0", features = ["derive", "rc"] }
thiserror = "2.0.18"
tracing = { version = "0.1.41", features = ["log"] }
uuid = { version = "1", features = ["v4", "serde"] }
weak-table = "0.3.2"

[dev-dependencies]
criterion = { version = "0.8", features = ["html_reports"] }
crossbeam-utils = "0.8"
test-log = "0.2.17"

[lints.clippy]
doc_markdown = "allow"
inline_always = "allow"
missing_errors_doc = "allow"
missing_panics_doc = "allow"
must_use_candidate = "allow"
needless_for_each = "allow"
pedantic = { level = "warn", priority = -1 }
similar-names = "allow"
transmute_ptr_to_ptr = "allow"

[[bench]]
name = "recv_throughput"
harness = false

[[bench]]
name = "router_throughput"
harness = false
