[package]
name = "ipc-channel-mux"
version = "0.0.4"
description = "IPC channel multiplexer"
authors = ["The Servo Project Developers"]
license = "MIT OR Apache-2.0"
repository = "https://github.com/glyn/ipc-channel-mux"
readme = "README.md"
edition = "2024"
# Keep this in sync with the msrv_build job in CI.
# This version may be `<=`, but not higher than the MSRV in the main servo project.
rust-version = "1.86.0"

[dependencies]
bincode = "1"
crossbeam-channel = "0.5"
fnv = "1.0.3"
futures-channel = { version = "0.3.31", optional = true }
futures-core = { version = "0.3.31", optional = true }
hashbag = "0.1.12"
ipc-channel = "0.20.2"
lazy_static = "1.5.0"
libc = "0.2.162"
log = "0.4.26"
serde = { version = "1.0", features = ["derive", "rc"] }
tracing = { version = "0.1.41", features = ["log"] }
uuid = { version = "1", features = ["v4", "serde"] }
weak-table = "0.3.2"

[dev-dependencies]
crossbeam-utils = "0.8"
test-log = "0.2.17"
